---
title: "Rをつかってみよう"
subtitle: "Kanazawa.R #1"
date: 2024-06-29
author: "伊東宏樹"
lang: ja
format:
  revealjs:
    theme: [dark, custom.scss]
slide-number: true
editor: visual
embed-resources: true
---

## はじめに

::: {style="margin-top: 2em; text-align: center; font-size: 200%; font-weight: bold;"}
Kanazawa.R にご参加<br /> ありがとうございます。
:::

## 本日の内容

-   Rの紹介

-   実演

-   まとめ

## 自己紹介

-   氏名: 伊東宏樹

## そもそも“R”とは

統計計算・グラフ作成向けのプログラミング言語&環境

オープンソース

### なぜ“R”という名前なのか

作者のファーストネーム(Robert Gentleman and Ross Ihaka)と、“S”言語から

## Rをつかっている人

-   学術

    -   医学・農学・生態学・心理学など

-   業務

    -   マーケティング（広告効果等）
    -   データ可視化（グラフ・ダッシュボード等）
    -   電子カルテサポートシステム（開業医）

## Rで できること

-   統計解析

-   機械学習

-   データの整形

-   可視化

## パッケージ

-   機能を拡張する関数やデータなどをまとめたもの

-   ユーザーが自分でパッケージを作れる。

-   CRAN (Comprehensive R Archive Network)

-   審査をとおるとCRANに登録される。

-   CRANには20828個のパッケージが登録されている（2024年6月2日現在）。

## Rコミュニティ

-   Tokyo.R, SappoRo.R, fukuoka.R など、各地で勉強会が開催されている。

-   Japan.R

## R vs. Python

-   統計分析のパッケージはRの方が豊富

-   機械学習はPythonの方が充実

### [RとPythonは仲良し](https://github.com/izunyan/practice-py-r/blob/main/pdf/tokyor100_20220723_yawarakakujira_公開版.pdf)

-   RStudioではPythonも同時に使える。

-   Pythonが得意なところをPythonで処理させたりできる。

## インストール

CRANからインストーラーをダウンロード

UNIX系ではソースからコンパイルしてもよい

## RStudio

統合開発環境 (IDE)

## 実演

RStudioに移動します。

## Rの情報

公式メーリングリスト群 (<https://www.r-project.org/mail.html>)

Tokyo.RのSlack <https://r-wakalang.slack.com>

<https://scrapbox.io/mandaRa/>

## 参考文献

### [Rで楽しむ統計](https://www.kyoritsu-pub.co.jp/book/b10003780.html)

奥村晴彦著, 共立出版

### [Rで学ぶ統計的データ解析](https://www.kspub.co.jp/book/detail/5186190.html)

林賢一・下平英寿著, 講談社

### [［改訂第2飯］RユーザーのためのRStudio［実践］入門](https://gihyo.jp/book/2021/978-4-297-12170-9)

松村優哉・湯谷啓明・紀ノ定保礼・前田和寛著, 技術評論社
